### ISSUE TITLE
Moar Behat tests

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#100] opened 2018-07-21 02:34 UTC
Referencing some of the tests present in GovCMS 7 (https://github.com/govCMS/govCMS/tree/7.x-2.x/build/tests/behat), we should start to expand on the Behat tests currently in place for GovCMS8

**Comment by tobybellwood** [comment] 2018-07-21 02:35
(note that some work is currently being undertaken by @pandaskii  on making those tests more PHP7 friendly

**Comment by simesy** [comment] 2020-01-14 06:43
Marking as dupe of https://github.com/govCMS/govCMS8/issues/14

**Closed as completed by simesy** 2020-01-14 06:43 UTC
