### ISSUE TITLE
Add Sitemap module to GovCMS8

### ISSUE THREAD

**Issue by pameeela** [govCMS/govcms8-installer#381] opened 2019-11-21 01:13 UTC
https://www.drupal.org/project/sitemap

(Note this module does not overlap with simple_sitemap, which generates an XML sitemap only. Sitemap module provides a human-readable sitemap.)

** What value does this module/package add to GovCMS?
Allows site builders/editors to easily generate and customise a sitemap.

** Please provide a brief outline of what this module does.
Allows users to configure a sitemap to display based on menu and taxonomy.

** Who does this module benefit:
[x] end users
[x] content editors
[x] site builders
[x] themers
[x] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
Currently the workaround is to create a page and add a menu block for each necessary menu. You could do the same with views blocks to display taxonomy.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
N/A

** What is the maintenance and support status of the module. Describe the issue queue activity.
The module is stable and actively maintained. There is only one open bug that is actively being worked on. Remaining issues are tasks or feature requests.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
'View published sitemap' to view the sitemap
'Administer sitemap' to configure it

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No. 

** Is the module designed to capture anonymous user data?
No.

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
Yes.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
This module is installed on pretty much every Drupal site I know of. 18,157 sites report using this module

** Additional information
Although there is a workaround, we feel strongly that GovCMS sites would benefit from its inclusion so that creation and modification of the sitemap is not a developer task.

**Comment by murraywoodman** [comment] 2019-11-24 23:15
This was also asked for a year or so ago. https://github.com/govCMS/govCMS8/issues/108#issuecomment-433754097

It would appear to be something very basic which was overlooked for GovCMS8.

**Comment by Belhendo** [comment] 2019-12-03 05:45
Hi Pam, thanks for your request and for your comment Murray. 

We acknowledge how useful this module is and that the code within the module itself is very simple. 

I've been provided advice however that it's possible to execute a shell command when uploading a file.  We're interested in making this module available and so we'd love to see this issue resolved so we can do so.

**Comment by simesy** [comment] 2019-12-03 06:31
I think this reply got crossed with https://github.com/govCMS/govCMS8/issues/382

**Comment by pameeela** [comment] 2019-12-03 06:32
Hi Belinda,

Thanks for replying but I think there’s been a mix up as that feedback doesn’t apply to sitemap module. 

Cheers
Pam

**Comment by Belhendo** [comment] 2019-12-03 22:08
Ahhh apologies, I have crossed my wires here! We're investigating your request still Pam and will be in touch soon.

**Comment by simesy** [comment] 2019-12-04 04:20
You say "Currently the workaround is to create a page and add a menu block for each necessary menu. You could do the same with views blocks to display taxonomy."

Could you explain why this is not viable? It means that the solution is using generic site building solutions and is less likely to be a vector for regressions.

**Comment by pameeela** [comment] 2019-12-04 04:33
It is viable! It is what we have been doing.

It just seems crazy to charge clients for this each time we do a build, when there is a module that would make it a ~15 min task. There are number of reasons that it can become quite complicated to use the workaround, and the cost adds up. 

There is also the simple optics of a client asking, 'Can we have a sitemap?' and answering 'Yes, but....'

The 'vector for regressions' seems misplaced here, as this is not a module with features being added regularly - it is a simple module that does a simple job. In fact, the current stable release is from Nov 2018. Having built Drupal sites for the better part of 10 years, I cannot recall a single issue ever cropping up with the sitemap module!

I also note there is already a patch in progress for D9: https://www.drupal.org/project/sitemap/issues/3042676

**Comment by simesy** [comment] 2019-12-04 05:05
I think it's valid to say that without simple modules like this, the cost of site build goes up. An example of something i can't easily in a saas site is recursively [building a taxonomy tree](https://git.drupalcode.org/project/sitemap/blob/8.x-1.x/src/SitemapHelper.php#L123), and instead you'd have untested complex code in the theme.

Personally if I did another saas site I'm telling them they can't have a sitemap, because this module isn't in there, i'm pointing the the editor to node/add and the block system and whatever. Then they will go to another vendor who will say yes and charge more. 

As it is the distro has too many modules and it is having an impact in various places, so the fact that it's viable to do this without the module has a big implication here unfortunately.

**Comment by brett-sargeant** [comment] 2019-12-04 05:10
It's one of those standard configuration things a Site admin should be able to do, similar to the other ones in the list I gave on the slack channel.

**Comment by simesy** [comment] 2019-12-04 05:16
Noting that this is just a visual page for users, and has nothing to do with the XML for google, it's perfectly possible for editors/admin to build a sitemap with views, blocks, menus, etc.

Except nested stuff (taxonomy, references) is a pain, speaking from experience there. It's practically impossible to do in the UI unless in a menu. (Love to hear solutions btw.)

**Comment by brett-sargeant** [comment] 2019-12-04 05:18
Ah for the days where I could just include a .htm in the page :D  (still can for 3 sites for a bit longer).

A module with simple configuration options would be best. It would allow for smaller agencies who might not have access to highly skilled staff.

**Comment by pameeela** [comment] 2019-12-04 05:19
It's possible for an editor/admin who has access to the code and knows how to export and commit config! I don't work with any editors/admins who meet that description.

**Comment by simesy** [comment] 2019-12-04 05:23
@pameeela  I'm seeing sites no longer export config for this reason. I have in a couple of cases advised clients to consider just exporting config as a backup, and leaving config/default empty. Although `config_ignore` can be a better middle ground...

@brett-sargeant technically you can serve static html out of your theme, the safest html there is. But the path is ugly.

**Comment by brett-sargeant** [comment] 2019-12-04 05:25
@pameeela if we can get it down to something like this and have it included in the appropriate training, then they should be able to meet most requirements, leaving high level stuff to contractors/outsourced providers. 
https://govcmschat.slack.com/archives/C3YKT5JJJ/p1574245161104600?thread_ts=1574223767.087200&cid=C3YKT5JJJ


@simesy after some of my other feature requests are added to the projects environment I had intended to request adding a task to export the config, to allow simpler stuff to be done in Gui and exported.

**Comment by simesy** [comment] 2019-12-04 05:30
Yeah i was hoping to PoC that... it needs some nodejs for the UI plus the job needs to write back to the repo. Actually I was thinking recently it would be better as a CI job that can be run manually, easier to manage write access to repos for the updated config

**Comment by brett-sargeant** [comment] 2019-12-04 05:38
The catch would be how it deals with branches.

**Comment by brett-sargeant** [comment] 2019-12-04 05:44
Actually I'll open a feature request for it now rather than wait. May as well add it to the list and maybe it will simplify working out the others.

**Comment by simesy** [comment] 2019-12-04 06:05
Nah, every environment has a branch, so it would create a new branch like config/BRANCH and open a merge request back to BRANCH. Or it would push back to the same branch.

Merge conflicts can suck, solved by only having one environment that you use for config exports.

**Comment by brett-sargeant** [comment] 2019-12-04 06:11
cool, because overwriting something in a branch you were working on would be a PITA. 

The request ticket is 4743.

Anyway circling back to the original request. It could help with configuring the module options, or the work around options. The module being the simplest way. checkboxes beating code for non devs.

**Comment by simesy** [comment] 2019-12-04 06:15
The sitemap saves config, so it's also effected by the config discussion as much as not using it (imo). Pamela is talking about it from a vendor pov, where it just means a faster build, and where you are deploying config from code as part of the build.

You're talking about it from an gov agency pov where it makes things "easy in the UI" - the config problem is not new for you and 4743 is the place to talk about it.

**Comment by simesy** [comment] 2019-12-04 06:19
I can't access 4743 btw.

**Comment by brett-sargeant** [comment] 2019-12-04 06:21
I'm effectively our vendor :D

**Comment by simesy** [comment] 2019-12-04 06:21
Ok "build and deploy for fixed price" vs "support and update for fixed brett"

**Comment by brett-sargeant** [comment] 2019-12-04 06:24
It does give me an interesting perspective at times.

Do you want me to add your lil engine email to the ticket cc?

**Comment by simesy** [comment] 2019-12-04 06:24
yeah I think that would work..

**Comment by brett-sargeant** [comment] 2019-12-04 06:25
done, hopefully I've typed it right.

**Comment by pameeela** [comment] 2019-12-04 07:27
I feel like we've kind of veered a bit off track here :)

I still feel very strongly that 'the ability to easily expose a sitemap' is a valid feature request. Frankly I'm blown away by this:

> Personally if I did another saas site I'm telling them they can't have a sitemap, because this module isn't in there, i'm pointing the the editor to node/add and the block system and whatever

I don't have any SaaS clients who would be capable of doing this sitebuilding, not to mention, the menu block approach ALWAYS needs theming.

But I guess it comes down to priorities and if this isn't one, I should just close the issue?

**Comment by simesy** [comment] 2019-12-04 07:33
To be clear, there hasn't been a govcms response yet. I'm just offering my opinion.

**Comment by simesy** [comment] 2019-12-04 07:34
I'm a big fan of this issue format because it allows a public conversation about how to solve the problems with saas so I'm happy to keep talking it over.

**Comment by simesy** [comment] 2019-12-04 07:36
> I don't have any SaaS clients who would be capable of doing this sitebuilding, not to mention, the menu block approach ALWAYS needs theming.

I know a few sites with internal capability or ongoing vendor support.

**Comment by pameeela** [comment] 2019-12-04 07:43
> The sitemap saves config, so it's also effected by the config discussion as much as not using it (imo).

1. Enable sitemap module
2. Add sitemap module to config_ignore

There are larger conversations to be had about config management in SaaS, but as it pertains to sitemap, it really isn't a factor.

And as I said, it's never as easy as adding a menu block. I've yet to do this where we didn't have to clean up the theming, because either the page layout is wonky with this random block or the menu styles are being applied in a weird way that doesn't work on a full page.

**Comment by Belhendo** [comment] 2019-12-18 01:19
Thank you for your request to add Sitemap module and thanks also for waiting for our response. Despite recognising that this module can improve usability for site builders and accessibility for users, the volume of mandatory releases in our backlog and our ongoing resourcing pressures mean that we are not able to prioritise the work required to incorporate ongoing releases of this module.  

Clarification for future readers: the requested module is for a customised HTML sitemap. This does not affect the existing XML sitemap module that is in the distribution.

**Closed as completed** 2020-01-15 01:59 UTC
Labels: enhancement, wontfix, Module
