### ISSUE TITLE
Sample content not published (fresh install)

### ISSUE THREAD

**Issue by NigelCunningham** [govCMS/govcms8-installer#183] opened 2019-01-07 04:09 UTC
I am using 1.0.0-alpha10 (916c72e79f4f), and chose to install sample content. Everything appeared to run to completion (no errors displayed) but the end result is that content created is in Draft state. I assume it's related to Workbench moderation being installed, but haven't done any debugging at the time of writing. Tested on my local machine and a trail Platform SH installation with the same result in both cases.

**Comment by gargsuchi** [comment] 2019-03-29 04:08
Duplicate of https://github.com/govCMS/govCMS8/issues/248

**Comment by gargsuchi** [comment] 2019-09-12 03:22
We should close this one - as #248 is closed. @tobybellwood

**Comment by tobybellwood** [comment] 2019-09-12 09:45
agree - fixed this one up

**Closed as completed by tobybellwood** 2019-09-12 09:45 UTC
